stages:
  - build

variables:
  IMAGE_NAME: "juadadev/backendproducts:latest"

# Job para construir la imagen Docker
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_TOKEN" docker.io
  script:
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
