stages:
  - build
  - push

variables:
  DOCKER_IMAGE: "juadadev/backendproducts"
  DOCKER_TAG: "latest"
  DOCKER_REGISTRY: docker.io
  DOCKER_DRIVER: overlay2 # Usar un driver adecuado para Docker-in-Docker

before_script:
  - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin docker.io

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t "$DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG" .

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push "$DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG"
  only:
    - main # Opcional: solo ejecuta en la rama master
