services:
  db:
    image: mysql:8.0
    container_name: productdb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Create automatically the database
    ports:
      - "3306:3306"
    volumes:
      - productdb_data:/var/lib/mysql
    networks:
      - products_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 10s

  fastapi_app:
    build: .
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONPATH: "/app"
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "8000:8000"
    networks:
      - products_network

networks:
  products_network:

volumes:
  productdb_data:
